# vim: set fdm=marker expandtab filetype=toml:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# Require ``brew install rmtrash``
repo = 'Shougo/vimproc.vim'
build = 'make'
if = '!exists("g:vscode")'

# Unite {{{
[[plugins]]
repo = 'Shougo/neoyank.vim'
lazy = 1
#on_path = '.*'
on_i = 1

[[plugins]]
repo = 'tsukkee/unite-tag'
depends = 'unite.vim'

#[[plugins]]
#repo = 'ujihisa/unite-colorscheme'
#depends = 'unite.vim'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

[[plugins]]
repo = 'sgur/unite-git_grep'
depends = 'unite.vim'

[[plugins]]
repo = 'Kocha/vim-unite-tig'
depends = 'unite.vim'
# }}}

# Text Operation {{{
[[plugins]]
repo = 'nishigori/increment-activator'

[[plugins]]
repo = 'vim-scripts/smartchr'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'itchyny/vim-cursorword'
# }}}

# Utility {{{
[[plugins]]
repo = 'nishigori/vim-multiple-switcher'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/urilib.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'thinca/vim-visualstar'
# }}}

# Completion {{{
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
# }}}

# Python {{{
[[plugins]]
repo = 'mitsuhiko/vim-jinja'
on_ft = [['python', 'jinja']]

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
lazy = 1
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/python.vim--Vasiliev'
if = '!exists("g:gui_oni")'
lazy = 1
on_ft = [['python', 'django']]
# }}}

# Ruby {{{
[[plugins]]
repo = 'tpope/vim-rbenv'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'rhysd/neco-ruby-keyword-args'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
lazy = 1
on_ft = 'ruby'
# }}}

# Lua {{{
[[plugins]]
repo = 'xolox/vim-misc'
on_ft = 'lua'

[[plugins]]
repo = 'vim-scripts/lua.vim'
lazy = 1
on_i = 1
on_ft = 'lua'
depends = 'vim-misc'
# }}}
