# vim: set fdm=marker expandtab filetype=toml:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# Require ``brew install rmtrash``
repo = 'Shougo/vimproc.vim'
build = 'make'

# Unite {{{
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'unite.vim'

[[plugins]]
repo = 'tacroe/unite-mark'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
#on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
lazy = 1
#on_path = '.*'
on_i = 1

[[plugins]]
repo = 'tsukkee/unite-tag'
depends = 'unite.vim'

[[plugins]]
repo = 'basyura/unite-converter-file-directory'
depends = 'unite.vim'

#[[plugins]]
#repo = 'ujihisa/unite-colorscheme'
#depends = 'unite.vim'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

[[plugins]]
repo = 'sgur/unite-git_grep'
depends = 'unite.vim'

[[plugins]]
repo = 'Kocha/vim-unite-tig'
depends = 'unite.vim'

#[[plugins]]
#repo = 'Shougo/unite-help'
#depends = 'unite.vim'


[[plugins]]
repo = 'osyo-manga/unite-quickrun_config'
depends = 'unite.vim'
# }}}

# Shell {{{
[[plugins]]
repo = 'Shougo/vimshell.vim'
lazy = 1
on_map = [['n', '<Plug>(vimshell_switch)']]

[[plugins]]
repo = 'yomi322/vim-gitcomplete'
depends = 'vimshell.vim'
# }}}

# Text Operation {{{
[[plugins]]
repo = 'nishigori/increment-activator'

[[plugins]]
repo = 'smartchr'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'itchyny/vim-cursorword'

#[[plugins]]
#repo = 'tpope/vim-surround'

#[[plugins]]
#repo = 't9md/vim-textmanip'
# }}}

# Utility {{{
[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'nishigori/vim-multiple-switcher'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/urilib.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'thinca/vim-visualstar'

#[[plugins]]
#repo = 'mattn/unite-nyancat'

#[[plugins]]
#repo = 'junegunn/vim-emoji'

#[[plugin]]
#repo = 'vim-scripts/copypath.vim'

#[[plugin]]
#repo = 'thinca/vim-openbuf'
# }}}

# Filer, Tags {{{
[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'majutsushi/tagbar'
# }}}

# Buffer, Status {{{
[[plugins]]
repo = 'itchyny/lightline.vim'

# TODO: たしか新しいvimでは不要になった記憶
#[[plugins]]
#repo = 'vim-scripts/PreserveNoEOL'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
depends = 'lightline.vim'

[[plugins]]
repo = 'tyru/current-func-info.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/syntastic'
# }}}

# Completion {{{
[[plugins]]
repo = 'Shougo/context_filetype.vim'
lazy = 1
on_path = '.*'

[[plugins]]
repo = 'Shougo/neocomplete'
lazy = 1
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
lazy = 1
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'
lazy = 1
on_i = 1

#[[plugins]]
#repo = 'mattn/emmet-vim'
#lazy = 1
#on_i = 1
#on_ft = 'html'
# }}}

# Go {{{
[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
lazy = 1
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
lazy = 1
on_ft = 'go'

[[plugins]]
repo = 'vim-jp/vim-go-extra'
lazy = 1
on_ft = 'go'
# }}}

# Lisp {{{
#[[plugins]]
#repo = 'aharisu/vim_goshrepl'
#lazy = 1
#on_ft = ''

#[[plugins]]
#repo = 'aharisu/vim-gdev'
#lazy = 1
#on_ft = ''
# }}}

# Python {{{
[[plugins]]
repo = 'zchee/deoplete-jedi'
lazy = 1
on_i = 1
on_ft = 'python'

[[plugins]]
# require ``pip install -U jedi`` but jedi configure is out of permission
repo = 'davidhalter/jedi-vim'
lazy = 1
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
lazy = 1
on_ft = 'python'

[[plugins]]
repo = 'mitsuhiko/vim-jinja'
on_ft = [['python', 'jinja']]

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
lazy = 1
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/python.vim--Vasiliev'
lazy = 1
on_ft = [['python', 'django']]
# }}}

# Ruby {{{
[[plugins]]
repo = 'tpope/vim-rbenv'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'rhysd/neco-ruby-keyword-args'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'ruby-matchit'
lazy = 1
on_ft = 'ruby'
# }}}

# PHP {{{
[[plugins]]
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = [['twig', 'html.twig', 'twig.html']]

[[plugins]]
repo = 'nishigori/vim-php-dictionary'
lazy = 1
on_i = 1
on_ft = 'php'

#[[plugins]]
#repo = 'nishigori/phpfolding.vim'
#lazy = 1
#on_ft = 'php'

#[[plugins]]
#repo = 'arnaud-lb/vim-php-namespace'
#lazy = 1
#on_ft = 'php'

# TODO: support to neocomplete
#[[plugins]]
#repo = 'nishigori/neocomplcache-phpunit-snippet'
#lazy = 1
#on_i = 1
#on_ft = 'php'
# }}}

# Lua {{{
[[plugins]]
repo = 'xolox/vim-misc'
on_ft = 'lua'

[[plugins]]
repo = 'vim-scripts/lua.vim'
lazy = 1
on_i = 1
on_ft = 'lua'
depends = 'vim-misc'
# }}}

# Makeup Languages {{{
[[plugins]]
repo = 'cespare/vim-toml'
lazy = 1
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
lazy = 1
on_ft = 'json'

[[plugin]]
repo = 'godlygeek/tabular'
lazy = 1

[[plugin]]
repo = 'plasticboy/vim-markdown'
lazy = 1
depends = 'tabular'
on_ft = [['markdown', 'mkd']]

[[plugins]]
repo = 'jtriley/vim-rst-headings'
lazy = 1
on_ft = [['python', 'rst', 'rest']]

[[plugins]]
repo = 'vim-scripts/css3'
lazy = 1
on_ft = 'css'

[[plugins]]
repo = 'tpope/vim-haml'
lazy = 1
on_ft = [['haml, scss']]
# }}}

# Other Programming Languages {{{
[[plugins]]
repo = 'rdolgushin/groovy.vim'
lazy = 1
on_ft = 'groovy'

#[[plugins]]
#repo = 'jimenezrick/vimerl'
#lazy = 1
#on_ft = 'erlang'

#[[plugins]]
#repo = 'ujihisa/ref-hoogle'
#lazy = 1
#on_ft = 'haskell'

#[[plugins]]
#repo = 'ujihisa/unite-haskellimport'
#lazy = 1
#on_ft = 'haskell'
# }}}

# Provisioning Tools {{{
[[plugins]]
repo = 'rodjek/vim-puppet'
lazy = 1
on_ft = 'puppet'

[[plugins]]
repo = 'puppetlabs/puppet-syntax-vim'
lazy = 1
on_ft = 'puppet'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
lazy = 1
on_ft = [['docker', 'dockerfile']]
# }}}
