# vim: set fdm=marker expandtab filetype=toml:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# Require ``brew install rmtrash``
repo = 'Shougo/vimproc.vim'
build = 'make'
if = '!exists("g:vscode")'

# Unite {{{
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'unite.vim'

[[plugins]]
repo = 'tacroe/unite-mark'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
#on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
lazy = 1
#on_path = '.*'
on_i = 1

[[plugins]]
repo = 'tsukkee/unite-tag'
depends = 'unite.vim'

#[[plugins]]
#repo = 'ujihisa/unite-colorscheme'
#depends = 'unite.vim'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

[[plugins]]
repo = 'sgur/unite-git_grep'
depends = 'unite.vim'

[[plugins]]
repo = 'Kocha/vim-unite-tig'
depends = 'unite.vim'
# }}}

# Text Operation {{{
[[plugins]]
repo = 'nishigori/increment-activator'

[[plugins]]
repo = 'vim-scripts/smartchr'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'itchyny/vim-cursorword'
# }}}

# Utility {{{
[[plugins]]
repo = 'nishigori/vim-multiple-switcher'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tyru/urilib.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'thinca/vim-visualstar'
# }}}

# Filer, Tags {{{
[[plugins]]
repo = 'Shougo/vimfiler.vim'
if = '!exists("g:vscode")'
# }}}

# Buffer, Status {{{
[[plugins]]
repo = 'itchyny/lightline.vim'
if = '!exists("g:vscode")'

# TODO: たしか新しいvimでは不要になった記憶
#[[plugins]]
#repo = 'vim-scripts/PreserveNoEOL'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
depends = 'lightline.vim'
if = '!exists("g:vscode")'

[[plugins]]
repo = 'tyru/current-func-info.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
# }}}

# Completion {{{
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'
lazy = 1
on_i = 1
# }}}

# Python {{{
[[plugins]]
repo = 'mitsuhiko/vim-jinja'
on_ft = [['python', 'jinja']]

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
lazy = 1
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/python.vim--Vasiliev'
if = '!exists("g:gui_oni")'
lazy = 1
on_ft = [['python', 'django']]
# }}}

# Ruby {{{
[[plugins]]
repo = 'tpope/vim-rbenv'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'rhysd/neco-ruby-keyword-args'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
lazy = 1
on_ft = 'ruby'
# }}}

# Lua {{{
[[plugins]]
repo = 'xolox/vim-misc'
on_ft = 'lua'

[[plugins]]
repo = 'vim-scripts/lua.vim'
lazy = 1
on_i = 1
on_ft = 'lua'
depends = 'vim-misc'
# }}}

# Makeup Languages {{{
[[plugins]]
repo = 'cespare/vim-toml'
lazy = 1
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
lazy = 1
on_ft = 'json'

[[plugin]]
repo = 'godlygeek/tabular'
lazy = 1

[[plugin]]
repo = 'plasticboy/vim-markdown'
lazy = 1
depends = 'tabular'
on_ft = [['markdown', 'mkd']]

[[plugins]]
repo = 'jtriley/vim-rst-headings'
lazy = 1
on_ft = [['python', 'rst', 'rest']]

[[plugins]]
repo = 'vim-scripts/css3'
lazy = 1
on_ft = 'css'

[[plugins]]
repo = 'tpope/vim-haml'
lazy = 1
on_ft = [['haml, scss']]
# }}}

# Other Programming Languages {{{
[[plugins]]
repo = 'rdolgushin/groovy.vim'
lazy = 1
on_ft = 'groovy'
# }}}

# Provisioning Tools {{{
[[plugins]]
repo = 'rodjek/vim-puppet'
lazy = 1
on_ft = 'puppet'

[[plugins]]
repo = 'puppetlabs/puppet-syntax-vim'
lazy = 1
on_ft = 'puppet'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
lazy = 1
on_ft = [['docker', 'dockerfile']]
# }}}
