cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'mas'
mas 'Xcode', id: 497799835
mas 'Slack', id: 803453959
mas 'Alfred', id: 405843582
mas '1Password', id: 443987910
mas 'LastPass', id: 926036361
mas 'TweetDeck', id: 485812721

tap 'caskroom/cask'
tap 'caskroom/versions'
cask 'adobe-reader'
cask 'apache-directory-studio'
cask 'dropbox'
cask 'flash'
cask 'gimp'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'vagrant'
cask 'virtualbox'
cask 'skype'
cask 'macvim-kaoriya'
cask 'iterm2'


brew 'ack'
brew 'xz'
brew 'pcre'
brew 'gettext'
brew 'autoconf'
brew 'icu4c'
brew 'openssl'
brew 'readline'
brew 'libtool'
brew 'bison'
brew 'pkg-config'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'libffi'
brew 'glib'
brew 'cairo'
brew 'gmp'
brew 'coreutils'
brew 'cpanminus'
brew 'libressl'
brew 'libssh2'
brew 'libsodium'
brew 'libpgm'
brew 'norm'
brew 'dos2unix'
brew 'libelf'
brew 'dwarfutils'
brew 'jpeg'
brew 'libtiff'
brew 'figlet'
brew 'harfbuzz'
brew 'pango'
brew 'fontforge'
brew 'webp'
brew 'gd'
brew 'gdbm'
brew 'gflags'
brew 'glew'
brew 'glm'
brew 'glog'
brew 'gnu-sed'
brew 'sdl2'
brew 'sdl2_image'
brew 'graphviz'


brew 'pstree'
brew 'gawk'


brew 'git'
brew 'mercurial'
brew 'ghq'
brew 'peco'
brew 'jq'
brew 'tmux'

cask 'java'
brew 'groovy'
brew 'gauche'
brew 'go'
brew 'python'
brew 'lua'
brew 'luajit'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pypy'
brew 'pypy3'
brew 'python3'
brew 'ruby'
brew 'ruby-build'
brew 'rbenv'
brew 'perl-build'
brew 'plenv'
brew 'llvm', args: ['with-clang', 'with-lld', 'with-rtti']
brew 'nodebrew'

brew 'homebrew/php/php71'
brew 'homebrew/php/php71-mcrypt'
brew 'homebrew/php/php71-opcache'
brew 'homebrew/php/php71-tidy'
brew 'php70'
brew 'php70-mcrypt'
brew 'php70-msgpack'
brew 'php70-opcache'
brew 'php70-tidy'

brew 'cscope'
brew 'ctags'
brew 'gotags'

brew 'sqlite'
brew 'wget'

brew 'zsh'
brew 'zplug'

brew 'packer'
brew 'terraform'

brew 'imagemagick'
brew 'imap-uw'
brew 'jemalloc'
brew 'lz4'
brew 'lzo'
brew 'lzop'
brew 'libarchive'
brew 'libevent'
brew 'libmagic'
brew 'libmemcached'
brew 'libmpc'
brew 'libtasn1'
brew 'libvpx'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'libzip'
brew 'mcrypt'
brew 'md5sha1sum'
brew 'sleuthkit'
brew 'osquery'
brew 'ossp-uuid'
brew 'popt'
brew 'rlwrap'
brew 'rpm2cpio'
brew 'rpm'
brew 'scons'
brew 'sl'
brew 'tbb'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tidy-html5'
brew 'tig'
brew 'tree'
brew 'unixodbc'
brew 'watch'
brew 'zlib'

tap 'osx-cross/avr'
brew 'osx-cross/avr/avr-binutils'
brew 'osx-cross/avr/avr-gcc'
brew 'osx-cross/avr/avr-libc'

#tap 'neovim/neovim'
#tap 'rogual/neovim-dot-app'
#brew 'neovim/neovim/neovim'

tap 'sanemat/font'
brew 'sanemat/font/ricty'


####################
# CommandLine Tools
###################
brew 'automake'
brew 'awscli'
brew 'amazon-ecs-cli'
brew 'bash'
brew 'bsdmake'
#brew 'ghc'
#brew 'cabal-install'
brew 'cmake'
brew 'curl', args: ['with-libressl']
brew 'wrk'
