#!/bin/sh

archive='php_manual_ja.tar.gz'

echo 'Getting PHP Manual files ...'
wget -q -O - http://php.net/get/php_manual_ja.tar.gz/from/jp.php.net/mirror >> $archive

echo 'Extract to disk from the PHP Manual files archive ...'
tar xzf $archive

echo 'Done.\n'

rm $archive

echo 'You have to copy `php-chunked-xhtml` to your specific dir'
echo 'ex.) \$vimrutime/ref/php'
