name: macos

on:
  push:
  pull_request:

jobs:
  make:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: make install
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make update
